name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g codecov nyc
      - run: npm install
      - run: npm run-script build
      - run: TZ=America/Vancouver npm test
      - run: TZ=America/Los_Angeles npm test
      - run: TZ=Africa/Nairobi npm test
      - run: TZ=Asia/Tokyo npm run-script test-ci
      - run: nyc report --reporter=json && codecov -t ${{ secrets.CODECOV_REPO_TOKEN }} -f coverage/*.json
